# SPDX-FileCopyrightText: 2023 SAP SE
#
# SPDX-License-Identifier: Apache-2.0
#
# This file is part of FEDEM - https://openfedem.org

name: Regression testing

on:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build FMU for Linux

    runs-on: ubuntu-latest

    steps:
      - name: Silence some advice and hint
        run: |
          git config --global advice.detachedHead false
          git config --global init.defaultBranch main

      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Configure main build
        run: cmake -B ./build -DCMAKE_BUILD_TYPE=Release

      - name: Build FMU library
        run: cmake --build ./build --target fedem_fmu

  build-linux:
    name: Build FMU for Windows

    runs-on: windows-latest

    steps:
      - name: Silence some advice and hint
        run: |
          git config --global advice.detachedHead false
          git config --global init.defaultBranch main

      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Configure main build
        run: cmake -B ./build -G "Visual Studio 17 2022"

      - name: Build FMU library
        run: cmake --build ./build --target fedem_fmu
